In [6]:
import numpy as np

In [7]:
mass1 = np.array([1, 2, 3], int)
mass2 = np.array([4, 5, 6], int)
print(mass1[1])

2


In [8]:
# Пример инициализации двумерного массива:
mass3 = np.array([[1, 2], [3, 4]], float)
mass4 = np.array([[5, 6], [7, 8]], float)

In [9]:
a = np.zeros((2, 4), int)
print(a)

[[0 0 0 0]
 [0 0 0 0]]


In [10]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
arr = np.arange(1, 10, 2)  # массив 1, 3, 5, 7, 9
print(arr)


[1 3 5 7 9]


In [12]:
print ('Среднее значение арифметическое = ' + str(mass3.mean()))

Среднее значение арифметическое = 2.5


In [14]:
# Создаем массив
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [15]:
print("Элемент [2, 3]:", arr[2, 3])
print("Элемент [2, 3]:", arr[2, 3])

Элемент [2, 3]: 12
Элемент [2, 3]: 12


In [18]:
print(mass1.shape)
print(mass1.dtype)


(3,)
int64


In [19]:
print(mass1 + mass2)
print(mass1 * mass2)


[5 7 9]
[ 4 10 18]
